language: python

python:
- '3.4'

before-install:
- pip install --upgrade pip

install:
- pip install -r requirements.txt

before_script:
- uname -a
- printenv | sort

script:
- date
- ls -al

deploy:
- provider: elasticbeanstalk
app: partypeople
env: partypeople-dev
bucket_name: partypeople-us-west-2-656991372336
region: us-west-2
access_key_id:
  secure: DtdrBO68Jn5kboLmXpryxRR02Pg4g87DBXjJWrxZo/0Rh/KJRRZUBy9UI0ZlMby8bfgyizgMOkxliJe9Zlpfgzrpg5TODeVXPH3H9abUquJ9E1Cx7QFGBuQ+vzIewls/ToTe9Vn/3+c/rSITSzUsp3KY0D0pGqiKnxE83Uy1y8NzCyjiBd5kL4Qa3ixK7EgxH1suUIsfCjaaQyok5lNucXloBCmn+V5FtmhG6RYB+5v60A1Zj355EYE3HlMHE2vBTT672wk0rj9ctW4BlRuVzPqLSSw1t63wQUUVG1JBiefX2cn/fkpGfUwJTdgzcW9HfId8XJrSPNlykql1NVmWKkMsXFJ8J23aqtqL6DFsqHDCWWnZDvNPWYvBzCbVkfXb5ZoV6BXqzqxuV5DoxVrikm+fb8Yu1qNLiPW9+CAmK1yTXUQMFxEFAEsnBP5MSv48lve5t1llVzURz/rtjKLaLqujJ1Xl3/NbsFHFj397pa4qtbH3Vv7zAfxT9XFmJC0ZLv3m3gGUbLGJJ1d6Uigy4sbTN6H1mez5OiQFS9etKWeczENv4EQSSrzDIH7++ImMc1VeObKdCeUDAcLZnwA7FBYNGAwPtg/Mp+vM0b+L3kKoxCCWaxAWww99UUfFplzaMq3kZQ03S+B3HyeqRGlXLJn++AZEzWaeSNouxDQ4lKQ=
secret_access_key:
  secure: ICObDPe2Lr0EQQTT3FVLpuHKnd67j6nRqfD6TrvMHNjKGmIRe2v8TQYJ1AuOHcTr3S9rAUTSap4jMsHFq5ggoECO/KtdzGMco1V0yosHwj+n1F2MQiUGQFaEyE3+WIyiEnJTenBt3tWLeH45DK9FAWgW8dyz2ThgKKUqe3M2YVeG0ZrYBFkRhQywbwSIWwl0g9AE3vyumgQxmioZJgDBnm6mi1lqJonsZNYLSJyoeCmJoI/E6VuQcRJcmSY8MgCi+WcWHRflGzvlej1DDv1KXq/olhU+GkXhUDYqXnR/+FCDAJFHJDvhOpaj2UURdC+L9RllBSDO5TyJ3445aVabJZyMURHjtOqVtkQDlV3d9SdFfhtm/E7znuFPnax0+WYd3+MmFqC6DT/U3YWuBvKpjVnIuLm7YgXZs+nM5wz8RiFbWL06bp8rdTTbR1lvrEuaE1mZoRuYzEWUoa14xJuuEbcLefx7/n76MnWQasgzHCNlHDebpIMfjv6etbEUn+w4W3wx7Iy5NRM3svlTgISv8bYCVcNMClEzP9AaQI5/u4vvI/24wCiD+G64+to627SMjcshFTfImOJtxCXSwEewCGSnjn/gKY4ueqzQR083yebBa2zBAWXn1QUUkUTNVZEV60V6LYf1lS5sAJLtXe+24n65aH78UgVOVYqfIdBYiGY=
on:
  branch: dev
- provider: elasticbeanstalk
  app: partypeople
  env: partypeople-prod
  bucket_name: partypeople-us-west-2-656991372336
  region: us-west-2
  access_key_id:
    secure: DtdrBO68Jn5kboLmXpryxRR02Pg4g87DBXjJWrxZo/0Rh/KJRRZUBy9UI0ZlMby8bfgyizgMOkxliJe9Zlpfgzrpg5TODeVXPH3H9abUquJ9E1Cx7QFGBuQ+vzIewls/ToTe9Vn/3+c/rSITSzUsp3KY0D0pGqiKnxE83Uy1y8NzCyjiBd5kL4Qa3ixK7EgxH1suUIsfCjaaQyok5lNucXloBCmn+V5FtmhG6RYB+5v60A1Zj355EYE3HlMHE2vBTT672wk0rj9ctW4BlRuVzPqLSSw1t63wQUUVG1JBiefX2cn/fkpGfUwJTdgzcW9HfId8XJrSPNlykql1NVmWKkMsXFJ8J23aqtqL6DFsqHDCWWnZDvNPWYvBzCbVkfXb5ZoV6BXqzqxuV5DoxVrikm+fb8Yu1qNLiPW9+CAmK1yTXUQMFxEFAEsnBP5MSv48lve5t1llVzURz/rtjKLaLqujJ1Xl3/NbsFHFj397pa4qtbH3Vv7zAfxT9XFmJC0ZLv3m3gGUbLGJJ1d6Uigy4sbTN6H1mez5OiQFS9etKWeczENv4EQSSrzDIH7++ImMc1VeObKdCeUDAcLZnwA7FBYNGAwPtg/Mp+vM0b+L3kKoxCCWaxAWww99UUfFplzaMq3kZQ03S+B3HyeqRGlXLJn++AZEzWaeSNouxDQ4lKQ=
  secret_access_key:
    secure: ICObDPe2Lr0EQQTT3FVLpuHKnd67j6nRqfD6TrvMHNjKGmIRe2v8TQYJ1AuOHcTr3S9rAUTSap4jMsHFq5ggoECO/KtdzGMco1V0yosHwj+n1F2MQiUGQFaEyE3+WIyiEnJTenBt3tWLeH45DK9FAWgW8dyz2ThgKKUqe3M2YVeG0ZrYBFkRhQywbwSIWwl0g9AE3vyumgQxmioZJgDBnm6mi1lqJonsZNYLSJyoeCmJoI/E6VuQcRJcmSY8MgCi+WcWHRflGzvlej1DDv1KXq/olhU+GkXhUDYqXnR/+FCDAJFHJDvhOpaj2UURdC+L9RllBSDO5TyJ3445aVabJZyMURHjtOqVtkQDlV3d9SdFfhtm/E7znuFPnax0+WYd3+MmFqC6DT/U3YWuBvKpjVnIuLm7YgXZs+nM5wz8RiFbWL06bp8rdTTbR1lvrEuaE1mZoRuYzEWUoa14xJuuEbcLefx7/n76MnWQasgzHCNlHDebpIMfjv6etbEUn+w4W3wx7Iy5NRM3svlTgISv8bYCVcNMClEzP9AaQI5/u4vvI/24wCiD+G64+to627SMjcshFTfImOJtxCXSwEewCGSnjn/gKY4ueqzQR083yebBa2zBAWXn1QUUkUTNVZEV60V6LYf1lS5sAJLtXe+24n65aH78UgVOVYqfIdBYiGY=
  on:
    branch: master